/**
 * LegalPages.jsx
 * Terms of Service and Privacy Policy — rendered inside the same retro pixel
 * window chrome as every other page in OnboardQuest.
 *
 * Routes:
 *   /terms    → <TermsOfService />
 *   /privacy  → <PrivacyPolicy />
 */

// ─── Shared pixel window wrapper ──────────────────────────────────────────────

function LegalWindow({ exeTitle, children }) {
  return (
    <div className="pixel-window" style={{ height: "100%" }}>
      <div className="pixel-titlebar">
        <span className="pixel-titlebar__title">{exeTitle}</span>
        <div className="pixel-titlebar__controls">
          <button className="pixel-titlebar__btn" aria-label="Minimise">_</button>
          <button className="pixel-titlebar__btn" aria-label="Maximise">□</button>
          <button className="pixel-titlebar__btn pixel-titlebar__btn--close" aria-label="Close">×</button>
        </div>
      </div>

      <div
        className="pixel-window__body"
        style={{ overflowY: "auto", display: "flex", flexDirection: "column", gap: 20 }}
      >
        {children}
      </div>

      <div className="pixel-window__statusbar">
        <span className="pixel-window__statusbar-segment">ONBOARDQUEST v1.0</span>
        <span className="pixel-window__statusbar-segment" style={{ marginLeft: "auto" }}>
          READ ONLY
        </span>
      </div>
    </div>
  );
}

// ─── Shared section component ─────────────────────────────────────────────────

function LegalSection({ title, children }) {
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
      <h2
        className="font-pixel"
        style={{
          fontSize:       "0.55rem",
          color:          "var(--col-blue)",
          letterSpacing:  "0.04em",
          borderBottom:   "2px solid var(--col-parchment)",
          paddingBottom:  "4px",
        }}
      >
        {title}
      </h2>
      <div
        style={{
          fontFamily: "var(--font-ui)",
          fontSize:   "1.05rem",
          lineHeight: 1.65,
          color:      "var(--col-ink)",
        }}
      >
        {children}
      </div>
    </div>
  );
}

// ─── Terms of Service ─────────────────────────────────────────────────────────

export function TermsOfService() {
  return (
    <LegalWindow exeTitle="TERMS_OF_SERVICE.EXE — ONBOARDQUEST">

      {/* Hero badge */}
      <div style={{ display: "flex", alignItems: "center", gap: 10, paddingBottom: 4 }}>
        <span style={{ fontSize: "1.6rem" }}>📜</span>
        <div>
          <div className="font-pixel" style={{ fontSize: "0.65rem", color: "var(--col-blue)" }}>
            TERMS OF SERVICE
          </div>
          <div style={{ fontFamily: "var(--font-ui)", fontSize: "0.95rem", color: "var(--col-muted)" }}>
            Effective: 1 January 2025 · Version 1.0
          </div>
        </div>
        <span className="pixel-badge pixel-badge--mint" style={{ marginLeft: "auto" }}>
          BINDING AGREEMENT
        </span>
      </div>

      <LegalSection title="1. ACCEPTANCE OF TERMS">
        By accessing or using OnboardQuest ("the Service"), you agree to be bound by these Terms
        of Service. If you do not agree, do not use the Service. OnboardQuest is provided as-is
        for educational and onboarding purposes.
      </LegalSection>

      <LegalSection title="2. PERMITTED USE">
        <p>You may use OnboardQuest to:</p>
        <ul style={{ paddingLeft: 20, marginTop: 6 }}>
          <li>Analyse codebases you own or have explicit permission to analyse.</li>
          <li>Share generated quest maps and briefings with your team.</li>
          <li>Integrate the API into internal developer tooling.</li>
        </ul>
        <p style={{ marginTop: 8 }}>You may <strong>not</strong> use OnboardQuest to:</p>
        <ul style={{ paddingLeft: 20, marginTop: 6 }}>
          <li>Analyse repositories without the owner's consent.</li>
          <li>Circumvent authentication or access controls.</li>
          <li>Resell or sub-license the Service without written permission.</li>
        </ul>
      </LegalSection>

      <LegalSection title="3. AI-GENERATED CONTENT">
        Quest briefings are generated by an AI model (IBM watsonx.ai Granite or OpenAI).
        AI output may be inaccurate, incomplete, or misleading. Always verify AI-generated
        architectural insights against the actual codebase. OnboardQuest is not liable for
        decisions made based on AI output.
      </LegalSection>

      <LegalSection title="4. GITHUB ACCESS & CREDENTIALS">
        When you provide a GitHub Personal Access Token (PAT) to analyse a private repository,
        that token is used solely for the single analysis request and is never stored on disk,
        logged, or transmitted to any third party. Tokens are held in memory for the duration
        of the HTTP request only.
      </LegalSection>

      <LegalSection title="5. INTELLECTUAL PROPERTY">
        OnboardQuest source code is released under the MIT Licence. The OnboardQuest name,
        logo, and MENTOR-8 mascot are trademarks of the project contributors. Generated quest
        maps derived from your own code remain your intellectual property.
      </LegalSection>

      <LegalSection title="6. DISCLAIMER OF WARRANTIES">
        THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. WE MAKE NO WARRANTIES
        REGARDING ACCURACY, RELIABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. USE AT YOUR
        OWN RISK.
      </LegalSection>

      <LegalSection title="7. LIMITATION OF LIABILITY">
        TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, ONBOARDQUEST CONTRIBUTORS SHALL
        NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING
        FROM USE OF THE SERVICE.
      </LegalSection>

      <LegalSection title="8. CHANGES TO TERMS">
        We may update these Terms at any time. Continued use of the Service after changes
        constitutes acceptance of the revised Terms. Check the version date above for the
        most recent revision.
      </LegalSection>

      <LegalSection title="9. CONTACT">
        Questions about these Terms? Open an issue on the OnboardQuest GitHub repository
        or email the maintainers at the address listed in the project README.
      </LegalSection>
    </LegalWindow>
  );
}

// ─── Privacy Policy ───────────────────────────────────────────────────────────

export function PrivacyPolicy() {
  return (
    <LegalWindow exeTitle="PRIVACY_POLICY.EXE — ONBOARDQUEST">

      {/* Hero badge */}
      <div style={{ display: "flex", alignItems: "center", gap: 10, paddingBottom: 4 }}>
        <span style={{ fontSize: "1.6rem" }}>🔒</span>
        <div>
          <div className="font-pixel" style={{ fontSize: "0.65rem", color: "var(--col-blue)" }}>
            PRIVACY POLICY
          </div>
          <div style={{ fontFamily: "var(--font-ui)", fontSize: "0.95rem", color: "var(--col-muted)" }}>
            Effective: 1 January 2025 · Version 1.0
          </div>
        </div>
        <span className="pixel-badge pixel-badge--blue" style={{ marginLeft: "auto" }}>
          DATA PROTECTION
        </span>
      </div>

      <LegalSection title="1. WHAT DATA WE COLLECT">
        <p>OnboardQuest is designed to collect as little data as possible:</p>
        <ul style={{ paddingLeft: 20, marginTop: 6 }}>
          <li><strong>Code snippets:</strong> Sent to the AI Mentor API in-memory only during a single session request. Never written to disk or a database.</li>
          <li><strong>Repository file paths:</strong> Used transiently during analysis. Not retained after the response is sent.</li>
          <li><strong>API keys / tokens:</strong> Passed in request bodies, used only for the current request, then discarded. Never logged.</li>
          <li><strong>Player state (level, XP, quests):</strong> Stored in React component state in your browser session only. Not transmitted to any server.</li>
        </ul>
      </LegalSection>

      <LegalSection title="2. WHAT WE DO NOT COLLECT">
        <ul style={{ paddingLeft: 20, marginTop: 4 }}>
          <li>We do not set tracking cookies.</li>
          <li>We do not use analytics scripts (no Google Analytics, Mixpanel, etc.).</li>
          <li>We do not collect names, email addresses, or personal identifiers.</li>
          <li>We do not build user profiles or sell data to third parties.</li>
        </ul>
      </LegalSection>

      <LegalSection title="3. AI PROVIDER DATA SHARING">
        When an AI API key is configured, code snippets are transmitted to the configured
        LLM provider (IBM watsonx.ai or OpenAI) to generate quest briefings. Each provider's
        own privacy policy governs how they handle that data. We recommend reviewing:
        <ul style={{ paddingLeft: 20, marginTop: 6 }}>
          <li>IBM watsonx.ai Data Privacy: ibm.com/cloud/privacy</li>
          <li>OpenAI Privacy Policy: openai.com/policies/privacy-policy</li>
        </ul>
        In offline mode (no API key configured), no data leaves your machine.
      </LegalSection>

      <LegalSection title="4. LOCAL ANALYSIS">
        When you analyse a local directory, all file reading happens on your machine
        via the local Node.js server process. No file content is transmitted externally
        unless you have configured an LLM provider (see Section 3).
      </LegalSection>

      <LegalSection title="5. GITHUB ANALYSIS">
        When you provide a GitHub URL, the repository is cloned to a temporary directory
        on your local machine (using git clone) or fetched via the GitHub API. The temporary
        directory is deleted immediately after analysis. Your GitHub PAT is used only for
        the single clone/fetch operation and is not stored.
      </LegalSection>

      <LegalSection title="6. LOGGING">
        The backend server logs minimal operational data to stdout (request paths, error
        messages). These logs are not persisted to disk in the default configuration.
        No user-identifying information is included in log output.
      </LegalSection>

      <LegalSection title="7. CHILDREN'S PRIVACY">
        OnboardQuest is intended for professional developer use. We do not knowingly collect
        information from children under 13. If you believe a child has submitted personal
        data, please contact us immediately.
      </LegalSection>

      <LegalSection title="8. YOUR RIGHTS">
        Since we do not persist personal data, there is no stored data to access, correct,
        or delete. If you have concerns about data processed by an AI provider, please
        contact that provider directly.
      </LegalSection>

      <LegalSection title="9. CHANGES TO THIS POLICY">
        We may update this Privacy Policy to reflect changes in our practices or applicable
        law. The effective date above will be updated with any revision. Significant changes
        will be noted in the project changelog.
      </LegalSection>

      <LegalSection title="10. CONTACT">
        Privacy questions? Open an issue on the OnboardQuest GitHub repository or contact
        the maintainers at the address listed in the project README.
      </LegalSection>
    </LegalWindow>
  );
}
